test: Interface for ServiceLoader must be public
Caused problems when running on Java 17:

java.util.ServiceConfigurationError: org.abego.commons.util.ServiceLoaderUtilTest$MyTestInterface: service type not accessible to unnamed module @55c53a33